version: '3.8'

services:
  # Exercise 1: Basic Environment Variables
  basic-app:
    build: ./exercise1
    container_name: env-basics
    ports:
      - "${BASIC_APP_PORT:-8081}:8080"
    # TODO: Configure environment variables for the basic-app service
    # HINT: Define APP_NAME, APP_ENV, DEBUG, and LOG_LEVEL variables
    # HINT: Use both hardcoded values and variable substitution ${VAR:-default}
    networks:
      - lab03_network

  # Exercise 2: Working with .env Files
  config-app:
    build: ./exercise2
    container_name: env-config
    ports:
      - "${CONFIG_APP_PORT:-8082}:8080"
    # TODO: Configure the service to use an environment file
    # HINT: Use the env_file directive to load from ./exercise2/.env.${ENV_NAME:-dev}
    networks:
      - lab03_network

  # Exercise 3: Multi-environment Compose Files
  # Only basic configuration here, overrides in separate files
  multi-env-app:
    build: ./exercise3
    container_name: multi-env
    ports:
      - "${MULTI_ENV_PORT:-8083}:8080"
    # TODO: Configure basic environment (development) settings here
    # HINT: Production settings will be in docker-compose.prod.yml
    networks:
      - lab03_network

  # Exercise 4: Secrets Management
  secrets-app:
    build: ./exercise4
    container_name: secrets-demo
    ports:
      - "${SECRETS_APP_PORT:-8084}:8080"
    # TODO: Configure environment variables for the secrets-app service
    # HINT: Include APP_NAME and APP_ENV variables
    # TODO: Configure the service to use an environment file
    # HINT: Use env_file directive to point to ./exercise4/.env.${ENV_NAME:-dev}
    # TODO: Configure secrets for the service
    # HINT: Reference the app_secret and db_password secrets defined below
    networks:
      - lab03_network

  # Database for all exercises
  postgres:
    image: postgres:14
    container_name: lab03-postgres
    # TODO: Configure database environment variables
    # HINT: Use variable substitution with defaults for POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - lab03_network

networks:
  lab03_network:
    driver: bridge

volumes:
  postgres_data:
    name: lab03_postgres_data

# Demo secrets for Exercise 4
# TODO: Configure Docker secrets for the secrets-app service
# HINT: Define file-based secrets for app_secret and db_password
secrets: # Define your secrets here (use the provided files in ./exercise4/secrets/ directory)
