version: '3.8'

services:
  # API Gateway - only service exposed to the outside world
  gateway:
    # TODO: Build the gateway service
    # HINT: Use the build directive to point to ./gateway
    # TODO: Configure ports for the gateway service
    # HINT: Map port 8080 to container port 8080
    # TODO: Configure environment variables for the gateway service
    # HINT: Set USERS_SERVICE_HOST, USERS_SERVICE_PORT, PRODUCTS_SERVICE_HOST, and PRODUCTS_SERVICE_PORT
    # TODO: Configure volumes for the gateway service
    # HINT: Mount ./gateway to /app
    # TODO: Configure service dependencies for the gateway service
    # HINT: Depends on users-service and products-service
    # TODO: Configure networks for the gateway service
    # HINT: Connect to the gateway-network

  # Users Service - only accessible through the gateway
  users-service:
    # TODO: Build the users service
    # HINT: Use the build directive to point to ./users-service
    # TODO: Configure environment variables for the users service
    # HINT: Set MONGO_HOST, MONGO_PORT, and MONGO_DB
    # TODO: Configure volumes for the users service
    # HINT: Mount ./users-service to /app
    # TODO: Configure service dependencies for the users service
    # HINT: Depends on db-service
    # TODO: Configure networks for the users service
    # HINT: Connect to gateway-network, service-network, and db-network

  # Products Service - only accessible through the gateway
  products-service:
    # TODO: Build the products service
    # HINT: Use the build directive to point to ./products-service
    # TODO: Configure environment variables for the products service
    # HINT: Set MONGO_HOST, MONGO_PORT, and MONGO_DB
    # TODO: Configure volumes for the products service
    # HINT: Mount ./products-service to /app
    # TODO: Configure service dependencies for the products service
    # HINT: Depends on db-service
    # TODO: Configure networks for the products service
    # HINT: Connect to gateway-network, service-network, and db-network

  # Database Service - only accessible by the service layer
  db-service:
    # TODO: Configure the database service
    # HINT: Use mongo:5.0 as the image
    # TODO: Configure volumes for the database service
    # HINT: Use a named volume for data and mount init scripts
    # TODO: Configure networks for the database service
    # HINT: Connect to the db-network

    # Define isolated network segments
networks:
  # Gateway network - connects the gateway to services
  gateway-network:
    driver: bridge

  # Service network - allows services to communicate with each other
  service-network:
    driver: bridge

  # DB network - isolates database access to services only
  db-network:
    driver: bridge

volumes:
  mongo-data:
