version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: networking-demo-frontend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - frontend-network
    # Frontend can only connect to backend via frontend-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: networking-demo-backend
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB=networkdemo
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - frontend-network
      - backend-network
    # Backend is connected to both frontend and database networks

  db:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network
    # Database is only accessible from backend via backend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
  # Each network provides isolation between tiers

volumes:
  mongo-data:
