version: '3.8'

services:
  frontend:
    # TODO: Build the frontend service
    # HINT: Use the build directive to point to ./frontend
    # TODO: Configure ports for the frontend service
    # HINT: Map port 8000 to container port 8000
    # TODO: Configure environment variables for the frontend service
    # HINT: Set BACKEND_HOST to backend and BACKEND_PORT to 8000
    # TODO: Configure volumes for the frontend service
    # HINT: Mount ./frontend to /app
    # TODO: Configure service dependencies for the frontend service
    # HINT: Depends on backend
    # TODO: Configure networks for the frontend service
    # HINT: Connect to the frontend-network

  backend:
    # TODO: Build the backend service
    # HINT: Use the build directive to point to ./backend
    # TODO: Configure environment variables for the backend service
    # HINT: Set MONGO_HOST to db, MONGO_PORT to 27017, and MONGO_DB to networkdemo
    # TODO: Configure volumes for the backend service
    # HINT: Mount ./backend to /app
    # TODO: Configure service dependencies for the backend service
    # HINT: Depends on db
    # TODO: Configure networks for the backend service
    # HINT: Connect to both frontend-network and backend-network

  db:
    # TODO: Configure the database service
    # HINT: Use mongo:5.0 as the image
    # TODO: Configure volumes for the database service
    # HINT: Use a named volume for data
    # TODO: Configure networks for the database service
    # HINT: Connect to the backend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
  # Each network provides isolation between tiers

volumes:
  mongo-data:
