version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    ports:
      - "8021:8000"
    environment:
      - FLASK_ENV=production
      - DEBUG=false
    restart: unless-stopped
