version: '3.8'

services:
  # Redis as a secrets store
  secrets-store:
    # TODO: Configure the Redis secrets store service
    # HINT: Use redis:alpine as the base image
    # HINT: Use a command to set a password for Redis
    # TODO: Specify the image for Redis
    # TODO: Set a command to require a password

    # TODO: Configure a volume for persistent Redis data
    # HINT: Use a named volume for Redis data

    # TODO: Configure environment variables for Redis
    # HINT: Set REDIS_PASSWORD using variable substitution

    # TODO: Configure networks for this service
    # HINT: Connect to the secrets-net network

    # TODO: Add a healthcheck for Redis
    # HINT: Use redis-cli ping as the test command

  # API to manage secrets
  secrets-api:
    # TODO: Configure the secrets API service
    # HINT: Use the build directive to point to ./secrets-api

    # TODO: Configure ports for the API service
    # HINT: Map port 8088 to container port 8000

    # TODO: Set up service dependencies
    # HINT: This service depends on the secrets-store

    # TODO: Configure environment variables for the API
    # HINT: Include Redis connection details and credentials

    # TODO: Configure networks for this service
    # HINT: Connect to the secrets-net network

  # Main application that uses secrets
  app:
    # TODO: Configure the main application service
    # HINT: Build from the current directory

    # TODO: Configure ports for the application
    # HINT: Map port 8003 to container port 8000

    # TODO: Set up service dependencies
    # HINT: This service depends on the secrets-api

    # TODO: Configure environment variables for the app
    # HINT: Include app configuration and API connection details

    # TODO: Configure networks for this service
    # HINT: Connect to the secrets-net network

    # TODO: Add a healthcheck for the application
    # HINT: Use curl to check the application health endpoint

    # TODO: Define the networks section
    # HINT: Create a bridge network called secrets-net

    # TODO: Define the volumes section
    # HINT: Create a named volume for Redis data persistence
