version: '3.8'

# Production overrides - apply with docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
services:
  # TODO: Configure production-specific build settings for the web service
  # HINT: Set production-specific build arguments and image tags
  web:
    # TODO: Configure build context and arguments
    # TODO: Set a production-specific image tag
    # TODO: Add environment file configuration
    # TODO: Set production-specific environment variables

    # TODO: Configure deployment settings for production scaling and reliability
    # HINT: Set replicas, resource limits, and restart policies
    # TODO: Configure replica count
    # TODO: Set appropriate resource limits and reservations
    # TODO: Configure restart policy

    # TODO: Configure health checks to ensure the service is functioning correctly
    # HINT: Use the /health endpoint to verify application health
    # TODO: Define health check command and parameters

    # TODO: Configure proper logging for production environment
    # HINT: Set log rotation to prevent disk space issues
    # TODO: Configure logging driver and options

    # TODO: Configure production-specific command
    # TODO: Configure security settings for production
    # HINT: Use read-only filesystem and restrict privileges
    # TODO: Enable read-only filesystem
    # TODO: Configure security options

    # TODO: Configure persistent storage for logs
    # TODO: Configure ports

  # TODO: Configure production-specific settings for Redis
  # HINT: Enable password protection and data persistence
  redis:
    # TODO: Configure Redis image
    # TODO: Set command with password protection and data persistence

    # TODO: Configure resource limits for Redis in production
    # HINT: Set appropriate CPU and memory limits
    # TODO: Configure resource limits and reservations
    # TODO: Configure restart policy

    # TODO: Configure health checks for Redis
    # HINT: Use redis-cli to verify Redis is responding
    # TODO: Define Redis health check command and parameters

    # TODO: Configure logging for Redis
    # HINT: Use the same logging configuration as the web service
    # TODO: Configure logging driver and options

    # TODO: Configure data persistence
    # TODO: Configure security settings for Redis
    # HINT: Use read-only filesystem where possible
    # TODO: Enable read-only filesystem
    # TODO: Configure temporary filesystem mounts for Redis

    # TODO: Define production-specific volumes
    # HINT: Include volumes needed only in production
volumes:
  # TODO: Define log volume
  # TODO: Define Redis data volume 
