version: "3.8"

services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - SERVICE2_NAME=hibye
    networks:
      - network1

  hibye:
    build:
      context: ./service2
      dockerfile: chokomoko
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    networks:
      - network2

networks:
  network1:
    driver: bridge
  network2:
    driver: bridge

# docker-compose -f docker-compose-isolated.yaml up --build 
