version: '3.8'

services:
  insecure-app:
    build: .
    container_name: secrets-insecure-standalone
    ports:
      - "8001:8000"
    environment:
      - APP_NAME=Insecure Secrets Demo
      - DB_USER=admin
      - DB_PASSWORD=insecure_password_123
      - API_KEY=1234567890abcdef
      - JWT_SECRET=supersecrettoken
      - DEBUG=true
