# TODO: Choose a base image for the web service
# HINT: Use a lightweight Python image

# TODO: Set up the working directory for the application
# HINT: Create a dedicated directory for the application

# TODO: Optimize Docker layer caching for dependencies
# HINT: Copy and install requirements before copying application code

# TODO: Copy application files into the container
# HINT: Copy all necessary files to run the Flask application

# TODO: Configure the container to expose the appropriate port
# HINT: Make sure the port matches what's used in the application

# TODO: Define the command to start the application
# HINT: Use Python to run the application file 