version: '3.8'

# This file will only be used when explicitly specified with:
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

# Production configuration
services:
  basic-app:
    environment:
      - APP_ENV=production
      - DEBUG=false
      - LOG_LEVEL=error
    restart: always
    deploy:
      replicas: 2

  config-app:
    env_file:
      - ./exercise2/.env.prod
    restart: always
    deploy:
      replicas: 2

  multi-env-app:
    # Define production environment overrides here
    environment:
      # Add production-specific environment variables

  secrets-app:
    # Define production environment overrides here
    environment: # Add production-specific environment variables
    env_file:
      - ./exercise4/.env.prod
    restart: always
    secrets:
      # Reference production secrets here

  postgres:
    # Define production environment overrides here
    environment: # Add production-specific environment variables
    env_file:
      - ./exercise4/.env.prod
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

# TODO: Define production-specific secrets
# HINT: Use the production secrets files in ./exercise4/secrets/ directory
secrets: # Define production secrets here
