version: '3.8'

# Production configuration
services:
  basic-app:
    environment:
      - APP_ENV=production
      - DEBUG=false
      - LOG_LEVEL=error
    restart: always
    deploy:
      replicas: 2

  config-app:
    env_file:
      - ./exercise2/.env.prod
    restart: always
    deploy:
      replicas: 2

  multi-env-app:
    environment:
      - APP_ENV=production
      - DEBUG=false
      - LOG_LEVEL=error
      - RELOAD=false
    restart: always
    deploy:
      replicas: 2

  secrets-app:
    environment:
      - APP_ENV=production
      - DEBUG=false
    env_file:
      - ./exercise4/.env.prod
    restart: always
    secrets:
      - app_secret
      - db_password
    deploy:
      replicas: 2

  postgres:
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password_prod
    secrets:
      - db_password_prod
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

# Production secrets
secrets:
  app_secret:
    file: ./exercise4/secrets/app_secret.prod.txt
  db_password:
    file: ./exercise4/secrets/db_password.prod.txt
  db_password_prod:
    file: ./exercise4/secrets/db_password.prod.txt
