version: '3.8'

services:
  web-service:
    build:
      context: ./web-service
      target: development
    ports:
      - "8030:8080"
    environment:
      - DEBUG=true
      - API_HOST=api-service
      - API_PORT=5000
    volumes:
      - ./web-service/app:/app
    depends_on:
      - api-service
    networks:
      - app-network

  api-service:
    build:
      context: ./api-service
      target: development
    ports:
      - "8031:5000"
    environment:
      - DEBUG=true
      - MONGO_HOST=db-service
      - MONGO_PORT=27017
      - MONGO_DB=apidb
    volumes:
      - ./api-service/app:/app
    depends_on:
      - db-service
    networks:
      - app-network

  db-service:
    build:
      context: ./db-service
      target: development
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
