version: '3.8'

services:
  web-service:
    build:
      context: ./web-service
      target: production
    ports:
      - "8030:8080"
    environment:
      - DEBUG=false
      - API_HOST=api-service
      - API_PORT=5000
    depends_on:
      - api-service
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  api-service:
    build:
      context: ./api-service
      target: production
    ports:
      - "8031:5000"
    environment:
      - DEBUG=false
      - MONGO_HOST=db-service
      - MONGO_PORT=27017
      - MONGO_DB=apidb
    depends_on:
      - db-service
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  db-service:
    build:
      context: ./db-service
      target: production
    environment:
      - MONGO_INITDB_DATABASE=apidb
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
