version: '3'

services:
  web:
    build:
      context: .
      args:
        - GIT_COMMIT=$(git rev-parse --short HEAD || echo "local")
        - BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        - APP_VERSION=1.0.0
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - PORT=8080
    volumes:
      - ./app.py:/app/app.py
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
